INSERT INTO film_genre (GENRE_ID, NAME)
VALUES(1, 'Комедия')
ON CONFLICT DO NOTHING;

INSERT INTO film_genre (GENRE_ID, NAME)
VALUES(2, 'Драма')
ON CONFLICT DO NOTHING;

INSERT INTO film_genre (GENRE_ID, NAME)
VALUES(3, 'Мультфильм')
ON CONFLICT DO NOTHING;

INSERT INTO film_genre (GENRE_ID, NAME)
VALUES(4, 'Триллер')
ON CONFLICT DO NOTHING;

INSERT INTO film_genre (GENRE_ID, NAME)
VALUES(5, 'Документальный')
ON CONFLICT DO NOTHING;

INSERT INTO film_genre (GENRE_ID, NAME)
VALUES(6, 'Боевик')
ON CONFLICT DO NOTHING;

INSERT INTO film_category (CATEGORY_ID, NAME)
VALUES(1, 'G')
ON CONFLICT DO NOTHING;

INSERT INTO film_category (CATEGORY_ID, NAME)
VALUES(2, 'PG')
ON CONFLICT DO NOTHING;

INSERT INTO film_category (CATEGORY_ID, NAME)
VALUES(3, 'PG_13')
ON CONFLICT DO NOTHING;

INSERT INTO film_category (CATEGORY_ID, NAME)
VALUES(4, 'R')
ON CONFLICT DO NOTHING;

INSERT INTO film_category (CATEGORY_ID, NAME)
VALUES(5, 'NC_17')
ON CONFLICT DO NOTHING;