INSERT INTO film_genre (ID, NAME)
VALUES(1, 'Комедия')
ON CONFLICT DO NOTHING;

INSERT INTO film_genre (ID, NAME)
VALUES(2, 'Драма')
ON CONFLICT DO NOTHING;

INSERT INTO film_genre (ID, NAME)
VALUES(3, 'Мультфильм')
ON CONFLICT DO NOTHING;

INSERT INTO film_genre (ID, NAME)
VALUES(4, 'Триллер')
ON CONFLICT DO NOTHING;

INSERT INTO film_genre (ID, NAME)
VALUES(5, 'Документальный')
ON CONFLICT DO NOTHING;

INSERT INTO film_genre (ID, NAME)
VALUES(6, 'Боевик')
ON CONFLICT DO NOTHING;

INSERT INTO film_category (ID, NAME)
VALUES(1, 'G')
ON CONFLICT DO NOTHING;

INSERT INTO film_category (ID, NAME)
VALUES(2, 'PG')
ON CONFLICT DO NOTHING;

INSERT INTO film_category (ID, NAME)
VALUES(3, 'PG-13')
ON CONFLICT DO NOTHING;

INSERT INTO film_category (ID, NAME)
VALUES(4, 'R')
ON CONFLICT DO NOTHING;

INSERT INTO film_category (ID, NAME)
VALUES(5, 'NC-17')
ON CONFLICT DO NOTHING;

ALTER TABLE users ALTER COLUMN user_id RESTART WITH 1;

ALTER TABLE films ALTER COLUMN film_id RESTART WITH 1;